import os
import time

while True:
    os.system("clear")
    print("🔴")
    print("⚫️")
    print("⚫️")
    time.sleep(5)
    os.system("clear")
    print("⚫️")
    print("🟡")
    print("⚫️")  
    time.sleep(2.5)
    for _ in range(3):
        os.system("clear")
        print("⚫️")
        print("🟡")
        print("⚫️")
        time.sleep(0.5)
        os.system("clear")
        print("⚫️")
        print("⚫️")
        print("⚫️")
        time.sleep(0.5)
    os.system("clear")
    print("⚫️")
    print("⚫️")
    print("🟢")
    time.sleep(5)
    os.system("clear")
    print("⚫️")
    print("🟡")
    print("⚫️")  
    time.sleep(2.5)
    for _ in range(3):
        os.system("clear")
        print("⚫️")
        print("🟡")
        print("⚫️")
        time.sleep(0.5)
        os.system("clear")
        print("⚫️")
        print("⚫️")
        print("⚫️")
        time.sleep(0.5)