import os 

import time
while True:
    os.system("clear")
    print("🔴")  
    print("⚪")  
    print("⚪")
    time.sleep(5)
    os.system("clear")
    print("⚪")  
    print("🟡")  
    print("⚪") 
    time.sleep(3)
    for _ in range(3):
        os.system("clear")
        print("⚪")  
        print("🟡")  
        print("⚪")
        time.sleep(1)
        os.system("clear")
        print("⚪")  
        print("⚪")  
        print("⚪")
        time.sleep(1)
    os.system("clear")
    print("⚪")  
    print("⚪") 
    print("🟢")  
    time.sleep(5)
    os.system("clear")
    for _ in range(3):
        os.system("clear")
        print("⚪")  
        print("🟡")  
        print("⚪")
        time.sleep(1)
        os.system("clear")
        print("⚪")  
        print("⚪")  
        print("⚪")
        time.sleep(1)